---
- name: Start the graphana container
  docker:
    detach: True
    image: "grafana/grafana:3.1.0"
    name: "grafana"
    ports: 
      - "3000:3000"
    state: started
    env: 
      INFLUXDB_HOST: "{{ influx_ip }}"
      INFLUXDB_PORT: 8086
      INFLUXDB_NAME: cadvisor
      INFLUXDB_USER: root
      INFLUXDB_PASS: root

- name: Waiting for the grafana service to become available
  wait_for:
    host: "{{ influx_ip }}"
    port: 3000
    state: started
    delay: 2
    timeout: 20

- name: Add the influx data source
  uri:
    url: http://{{ influx_ip }}:3000/api/datasources
    user: admin
    password: admin
    force_basic_auth: yes
    body_format: json
    HEADER_Content-Type: application/json
    method: POST
    status_code: 200,500
    # we workaround this issue :
    # https://github.com/ansible/ansible-modules-core/issues/265
    # by adding an empty space at the beginning of the json ...
    body: " { \"name\": \"influx\", \"type\": \"influxdb\", \"url\": \"http://{{ influx_ip }}\", \"access\": \"proxy\", \"database\": \"cadvisor\", \"user\": \"root\", \"password\": \"root\", \"isDefault\": true }"
